---
# tasks file for ssl

- name: Install Openssl
  yum: name=openssl-devel state=present

- name: Make directory for files
  file: path=/etc/ssl/xip.io state=directory mode=0755

- name: generates private rsa key
  command: openssl genrsa -out /etc/ssl/xip.io/xip.io.key 1024

- name: Create certificate
  command: openssl req -new -subj "/C=US/ST=Florida/L=Orlando/O=IT/CN=seeddms.project"  -key /etc/ssl/xip.io/xip.io.key                   -out /etc/ssl/xip.io/xip.io.csr

- name: signs keys
  command: openssl x509 -req -days 365 -in /etc/ssl/xip.io/xip.io.csr                     -signkey /etc/ssl/xip.io/xip.io.key                     -out /etc/ssl/xip.io/xip.io.crt

- name: create ".pem" file for HAProxy
  shell: cat /etc/ssl/xip.io/xip.io.crt /etc/ssl/xip.io/xip.io.key            | sudo tee /etc/ssl/xip.io/xip.io.pem

- name: restart haproxy
  service: name=haproxy state=restarted
                                          
